announcements/announce/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from . import views

# List of urls for the announce app. The login required wrappers are stated here as we're using class based views.
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^add/$', login_required(views.AnnouncementCreate.as_view()), name='announcement_add'),
    url(r'^update/(?P<pk>[0-9]+)/$', login_required(views.AnnouncementUpdate.as_view()), name='announcement_update'),
]

announcements/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as aviews
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.conf import settings

urlpatterns = [
    url(r'^announce/', include('announcements.announce.urls', namespace="announce")),
    url(r'^login/$', aviews.login, name='login'),
    url(r'^logout/$', aviews.logout, { 'next_page': 'announce:index' } , name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^.*$', RedirectView.as_view(url=('%s/%s'%(settings.MYURL,'announce/')), permanent=False), name='redirect_to_index')
]

announcements/announce/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.template import engines, Context
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
#from announcements import urls

# Models for Pawsey Supercomputing Centre Announcement System.

# Persons responsible for resources
class Owner(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField()
    phone = models.CharField(max_length=18)

    def __unicode__(self):
        return self.name

# Division of the organisation responsible for the resource and the announcement
class Silo(models.Model):
    name = models.CharField(max_length=128)
    owner = models.ForeignKey(Owner)

    def __unicode__(self):
        return self.name

# Physical location of the resources
class Location(models.Model):
    name = models.CharField(max_length=128)

    def __unicode__(self):
        return self.name

# Audiences (email lists, stored as an email address) for the announcements
class Audience(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=256)
    maillist = models.EmailField()

    def __unicode__(self):
        return self.name

# Resources available to announce about
class Resource(models.Model):
    name = models.CharField(max_length=128)
    silo = models.ForeignKey(Silo)
    location = models.ForeignKey(Location)
    audience = models.ManyToManyField(Audience)

    def __unicode__(self):
        return self.name

# Template store (in django template language)
class Template(models.Model):
    name = models.CharField(max_length=64)
    html = models.TextField()
    text = models.TextField()

    def __unicode__(self):
        return self.name

# Announcement Store
class Announcement(models.Model):
    subject = models.CharField(max_length=1024)
    reference = models.CharField(max_length=64, unique=True)
    service = models.ManyToManyField(Resource)
    body = models.TextField()
    template = models.ForeignKey(Template)
    dateTimeCreated = models.DateTimeField(auto_now_add=True, editable=False)
    createdBy = models.ForeignKey(User, editable=False, null=True)
    inactive = models.BooleanField(default=False)

    def __unicode__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse('announce:detail', kwargs={'pk': self.pk})

    # Generate list of comma seperated, non repeating, owner for services listed in the announcement.
    def get_serviceowners(self):
        owners = [] 
        for service in self.service.all():
            if not service.silo.owner.name in owners:
                owners.append(str(service.silo.owner.name))
        ownerlist = ', '.join(owners)
        return ownerlist

    # Generate list of comma seperated, non repeating, names for services listed in the announcement.
    def get_servicenames(self):
        names = [] 
        for service in self.service.all():
            if not service.name in names:
                names.append(str(service.name))
        namelist = ', '.join(names)
        return namelist

    # Generate list of comma seperated, non repeating, locations for services listed in the announcement.
    def get_servicelocations(self):
        names = [] 
        for service in self.service.all():
            if not service.location.name in names:
                names.append(str(service.location.name))
        namelist = ', '.join(names)
        return namelist

    # This is the money function. Here we actually send out the announcements to the intended audience. Each audience once.
    def send_email(self):
        django_engine = engines['django']
        html_template = django_engine.from_string(self.template.html)
        text_template = django_engine.from_string(self.template.text)
        
        context = Context({'reference': self.reference, 
            'dateTimeCreated': self.dateTimeCreated, 
            'serviceOwners': self.get_serviceowners(), 
            'serviceNames': self.get_servicenames(), 
            'serviceLocations': self.get_servicelocations(), 
            'body': self.body })

        html_body = html_template.render(context)
        text_body = html_template.render(context)

        subject = self.subject
        from_email = settings.SERVER_EMAIL
        # Create a list of email addresses to send to and avoid any repeats
        to_emails = []
        for service in self.service.all():
            for audience in service.audience.all():
                if not audience.maillist in to_emails:
                    to_emails.append(str(audience.maillist))

        # Send the emails to the destinations as individual emails
        for to in to_emails:
            msg = EmailMultiAlternatives(subject, text_body, from_email, [to])
            msg.attach_alternative(html_body, "text/html")
            msg.send()

        self.inactive=False
        self.save()

# Adding form classes here

# Form for adding and modifying announcements
class AnnouncementForm(ModelForm):
    class Meta:
        model = Announcement
        fields = ['subject', 'reference', 'service', 'template']

announcements/announce/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from .models import *

# Views for the non-admin (main) part of the app

# Summary list of the last few announcements, meant for public view.
class IndexView(generic.ListView):
    template_name = 'announce/index.html'
    context_object_name = 'latest_announcements_list'

    def get_queryset(self):
        """return the last 10 active Announcements"""
        """Miss out inactive Announcements if user is not logged in"""
        if self.request.user.is_authenticated():
            return Announcement.objects.order_by('-dateTimeCreated')[:10]
        else:
            return Announcement.objects.exclude(inactive=True).order_by('-dateTimeCreated')[:10]

# Detailed view of a particular announcement
class DetailView(generic.DetailView):
    model = Announcement
    queryset = Announcement.objects.exclude(inactive=True)
    context_object_name = 'announcementObject'
    template_name = 'announce/detail.html'
    # Restrict access to view inactive announcements to logged in users only.
    def get_queryset(self):
        if self.request.user.is_authenticated():
            return self.model._default_manager.all()
        else:
            return self.queryset.all()

# Announcement creation form (urls.py restricts this to logged in users)
class AnnouncementCreate(CreateView):
    model = Announcement
    fields = ['subject', 'reference', 'service', 'template', 'body']
    template_name = 'announce/add.html'

    def form_valid(self, form):
        # If we pressed the send email button then we should send an email
        # Also mark the announcement as inactive if it's a draft
        self.object = form.save()
        print self.object
        if '_send' in self.request.POST:
            # send email
            self.object.send_email()
        elif '_draft' in self.request.POST:
            # mark as inactive
            self.object.inactive=True

        return super(AnnouncementCreate, self).form_valid(form)

# Announcement updating form (urls.py restricts this to logged in users)
class AnnouncementUpdate(UpdateView):
    model = Announcement
    fields = ['subject', 'reference', 'service', 'template', 'body']
    template_name = 'announce/update.html'

    def form_valid(self, form):
        # If we pressed the send email button then we should send an email
        # Also mark the announcement as inactive if it's a draft
        self.object = form.save()
        print self.object
        if '_send' in self.request.POST:
            # send email
            self.object.send_email()
        # Commented out. We'll leave withdrawing announcements for the admin
        # app for the moment
        #elif '_draft' in self.request.POST:
        #    # mark as inactive
        #    self.object.inactive=True

        return super(AnnouncementUpdate, self).form_valid(form)

announcements/announce/templates/announce/add.html
{% extends "announce/base.html" %}

{% block title %}Pawsey Announcement Management System{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-6">
    <h4>Announcement Creation</h4>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
  <table>
  <form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <tr><td><input type="submit" value="Save Draft" name="_draft" /></td><td align="right"><input type="submit" value="Send Email" name="_send" /></td></tr>

    </table>
  </form>
  </div>
</div>
{% endblock %}

announcements/announce/templates/announce/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'announce/css/pawsey.css' %}" />
    <title>{% block title %}Pawsey Announcement Management System{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
    <meta name="Robots" content="noindex, nofollow" >
    <meta name="GOOGLEBOT" content="noarchive" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <div class="container">
        <img src="{% static 'announce/images/PawseyLogoHorizontal.png' %}" alt="Pawsey Supercomputing Centre">
        <h2>Announcements</h2>
        
        <hr>
        {% block content %}{% endblock %}
        {% if perms.announce %}
                 <a href="{% url 'admin:logout' %}">Logout</a>&nbsp;&nbsp;&nbsp;&nbsp;  
        {% endif %}
        {% if request.resolver_match.url_name != 'index' %}
        <a href="{% url 'announce:index' %}">Back to Index</a>
        {% endif %}
        <hr>
        <small>Copyright Pawsey Supercomputing Centre 2015 <a href="http://www.pawsey.org.au/">www.pawsey.org.au</a></small>
    </div>

</body>
</html>

announcements/announce/templates/announce/delete.html
{% extends "announce/base.html" %}

{% block title %}Pawsey Announcement Management System{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-6">
    <h4>Announcement Creation</h4>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
  <form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
  </form>
  </div>
</div>
{% endblock %}

announcements/announce/templates/announce/detail.html
{% extends "announce/base.html" %}

{% block title %}Pawsey Announcement Management System{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-6">
    <h4>Announcement Detail for {{ announcementObject.reference }}</h4>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">

{% if announcementObject %}
        <table border="2" >
        <tr>
        <td>Reference: {{ announcementObject.reference }} </td><td>Date/Time Created: {{ announcementObject.dateTimeCreated }} </td>
        </tr><tr>
        <td>{{ announcementObject.subject }}</td><td>Service(s): {{ announcementObject.get_servicenames }} </td>
        </tr><tr>
        <td>Owner(s): {{ announcementObject.get_serviceowners }} </td> <td>Location(s): {{ announcementObject.get_servicelocations }} </td>
        </tr><tr>
        <td style="height:200px;" colspan="2">{{ announcementObject.body }}</td>
        </table>
{% else %}
    <p>No recent announcements found</p>
{% endif %}
     <div align="right"><a href="{% url 'announce:index' %}">Go back</a></div>
  </div>
</div>
{% endblock %}

announcements/announce/templates/announce/index.html
{% extends "announce/base.html" %}

{% block title %}Pawsey Announcement Management System{% endblock %}

{% block content %}
{% if latest_announcements_list %}

<div class="row">
  <div class="col-lg-6">
    <h4>Most Recent Pawsey Supercomputing Centre Announcements</h4>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
   {% if perms.announce %}
   <a href="{% url 'announce:announcement_add' %}">Create New Announcement</a>
   {% endif %}
   <ul>
   {% for announcement in latest_announcements_list %}
        <li>Ref {{ announcement.reference }} {{ announcement.dateTimeCreated }} - <a href="{% url 'announce:detail' announcement.id %}">{{ announcement.subject }}</a>
        {% if perms.announce %}
         - <a href="{% url 'announce:announcement_update' announcement.id %}">Edit</a>
        {% endif %}
        </li>
   {% endfor %}
    </ul>
  </div>
</div>
{% else %}
    <p>No recent announcements found</p>
{% endif %}
{% endblock %}

announcements/announce/templates/announce/update.html
{% extends "announce/base.html" %}

{% block title %}Pawsey Announcement Management System{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-6">
    <h4>Announcement Editing</h4>
  </div>
</div>
<div class="row">
  <div class="col-lg-6">
  <table>
  <form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <tr><td><input type="submit" value="Save Draft" name="_draft" /></td><td align="right"><input type="submit" value="Send Email" name="_send" /></td></tr>

    </table>
  </form>
  </div>
</div>
{% endblock %}